### ISSUE TITLE
CustomInsightsFunction fails due to aws-sdk

### ISSUE THREAD

**Issue by FritjofH** [aws-samples/aws-security-hub-summary-email#9]
When deploying following the instructions the cloudformation creation hangs due to the CustomInsightsFunction lambda failing.

```
{
    "errorType": "Error",
    "errorMessage": "Cannot find module 'aws-sdk'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/var/task/index.js",
        "/var/runtime/index.mjs"
    ],
    "stack": [
        "Error: Cannot find module 'aws-sdk'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/index.mjs",
        "    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)",
        "    at Module._load (node:internal/modules/cjs/loader:986:27)",
        "    at Module.require (node:internal/modules/cjs/loader:1233:19)",
        "    at require (node:internal/modules/helpers:179:18)",
        "    at exports.handler (/var/task/index.js:7:14)",
        "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29)"
    ]
}
```

**Comment by lawtonpittenger** [comment]
Hello,
The code has been updated to create the Security Hub insights using CloudFormation. Closing this issue now.
